package io.github.palexdev.devutils.services;

public class ServicesDescriptions {
    //================================================================================
    // Static Properties
    //================================================================================
    public static final String ICOMOON_SERVICE = """
        This service's purpose is to convert icon fonts generated by the IcoMoon web app
        to a list of constants to be used in Java enumerators. All constants will have the
        icon's identifier, also called 'description', and the code point which is the unicode
        identifier in the font.
        """;

    //================================================================================
    // Constructors
    //================================================================================
    private ServicesDescriptions() {
    }
}
